apiVersion: v1
imagePullSecrets:
- name: build-bot-dockercfg-fwgxk
kind: ServiceAccount
metadata:
  name: vcs-trigger
  namespace: nicola-bertoli-pipelines-project
  resourceVersion: "5333566"
  selfLink: /api/v1/namespaces/nicola-bertoli-pipelines-project/serviceaccounts/build-bot
  uid: f20f3cd5-5fe6-44a9-8563-4e7946ee759e
secrets:
- name: build-bot-dockercfg-fwgxk
- name: build-bot-token-xfpcv
- name: quay-io-credentials

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vcs-trigger
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vcs-trigger
subjects:
  - kind: ServiceAccount
    name: vcs-trigger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vcs-trigger


