apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-assignment-pipeline-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: buildah-assignment-pipeline
  params:
  - name: image-repo
    value: quay.io/nicolabe92/buildah-assignment
  - name: app-name
    value: buildah-assignment
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi