apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: buildah-assignment
  app.kubernetes.io/instance: buildah-assignment-instance
  app.kubernetes.io/name: buildah-assignment
